# Generated by Django 5.1.4 on 2024-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.TextField(blank=True),
        ),
    ]
